// Generated by scripts/generate-firebase-config.js - DO NOT COMMIT
window.__FIREBASE_CONFIG__ = {
  apiKey: "AIzaSyBys1J3Ac2grNDOyRSU_D9uYdiqx7HUGTQ",
  authDomain: "architech-project-9b91e.firebaseapp.com",
  projectId: "architech-project-9b91e",
  storageBucket: "architech-project-9b91e.firebasestorage.app",
  messagingSenderId: "988900377949",
  appId: "1:988900377949:web:1cb749c1a502cbc9d054b4",
  measurementId: "G-BBHC6F9JTY"
};
