name: Inject Firebase config and build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  inject-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (optional, used if you have a build step)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ensure js directory exists
        run: mkdir -p js

      - name: Inject Firebase config (writes js/firebase-config.local.js)
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          cat > js/firebase-config.local.js <<'EOF'
          // Generated by CI - do not commit
          window.__FIREBASE_CONFIG__ = {
            apiKey: "${FIREBASE_API_KEY}",
            authDomain: "${FIREBASE_AUTH_DOMAIN}",
            projectId: "${FIREBASE_PROJECT_ID}",
            storageBucket: "${FIREBASE_STORAGE_BUCKET}",
            messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
            appId: "${FIREBASE_APP_ID}",
            measurementId: "${FIREBASE_MEASUREMENT_ID}"
          };
          EOF

      - name: Show generated file (sanity)
        run: sed -n '1,120p' js/firebase-config.local.js || true

      - name: Install & build (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm ci
            if npm run | grep -q "build"; then
              npm run build
            else
              echo "No build script defined in package.json"
            fi
          else
            echo "No package.json found: skipping npm build"
          fi

      # Deploy to Firebase Hosting (requires FIREBASE_TOKEN secret)
      - name: Deploy to Firebase Hosting
        if: ${{ secrets.FIREBASE_TOKEN != '' }}
        uses: w9jds/firebase-action@v12
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      #- name: Rsync deploy to server
      #  if: secrets.DEPLOY_HOST != ''
      #  env:
      #    DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
    